%%{init: {"theme":"default","themeVariables": {"background":"#ffffff","fontSize":"14"}}}%%
flowchart LR
subgraph Comments [Comments / Legend]
  direction LR
  style Comments fill:#f9fafb,stroke:#e5e7eb,color:#0f172a,stroke-width:1px;
  note1["Note: This flow is triggered by Approval Event and will Only receive JourneyId as input. The flow is very similar to screening flow except that it uses JourneyId in the initial request event instead of current {entities} in Screening Journey. In the Approval Flow , Only the main Entity is processed for Offboarding.
  The idea is to build re-usable Durable Activity Functions which will be orchestrated using different Orchestration Functions based on the business flow ( cancel flow, screening flow , approval flow etc)"]:::footer
end

%% Shared styles (matching AlertsFlow)
classDef step fill:#ffffff,stroke:#2b6cb0,color:#0f172a,stroke-width:1px;
classDef decision fill:#fff7ed,stroke:#d97706,color:#92400e,stroke-width:1px;
classDef loop fill:#f0f9ff,stroke:#60a5fa,color:#0f172a,stroke-width:1px;
classDef footer fill:#ffffff,stroke:none,color:#0f172a;
subgraph MainFlow [Main Flow]
   direction TB
  A[Receive HTTP POST due to Approval Event via Hub API Gateway]:::step --> B[Respond HTTP Status 200 immediately]:::step
  B --> B0["Indentify the Event Type using the Approval Event payload and Execute the appropriate Durable Function Orchestration"]:::step
  B0 --> D["Store payload in database in **RequestResponsePayload** Table in DB"]:::step
  D --> E["Create SuperGraph using GraphQL with **{RequestId}**, **{JourneyId}** and Only Main **{EntityId}**   and the **{customStatus=Offboarding}** for the Journey"]:::step

  E --> ConvertToXML["Convert the Json to XML for Call to NetReveal."]:::step
  ConvertToXML --> CallNetReveal["Call NetReveal Screening API with XML payload for Main **{EntityId}** and **{CustomerStatusCode}=INACTIVE** "]:::step
  CallNetReveal --> SaveNetRevealResponse["Save NetReveal Response AlertId in <b>RequestResponsePayload</b> Table in DB against current entity **{entityId}**, **{JourneyId}**, **{BatchId}**. "]:::step
  
  SaveNetRevealResponse --> P[End process - No response sent back to FenX]:::footer
end

style MainFlow stroke-dasharray: 5 5

%% Decision between main and error blocks
IfError{if error?}:::decision

%% Error handling block to the right
subgraph ErrorHandler [Error handling]
  direction TB
  EH1[Log Error to Error Log. No call to Receptor Since the Journey is completed.]:::step
  
end

style ErrorHandler fill:#ffe6e6,stroke:#ff0000,stroke-dasharray: 5 5

%% Connections: only between blocks (not individual nodes)
Comments ~~~MainFlow
MainFlow -.-> IfError
IfError -.-> ErrorHandler